### ISSUE TITLE
[Question] Could adding type to P.union be shorter?

### ISSUE THREAD

**Issue by jakubgosk** [gvergnaud/ts-pattern#103]
Hi,
So I found out about that lovely lib today, immediately installed it and while using P.union I found typing that one quite unusual.

For example:
```
type SomeLongAssNameType = 'red' | 'orange' | 'yellow' | 'green' | 'blue' | 'indigo' | 'violet';

match(color)
    .with('red', () => 'it is red')
    .with('orange', () => 'it is orange')
    .with(P.union('yellow', 'green'), () => 'it is yellow or green')
    .with(
      P.union('blue', 'indigo', 'violet', 'something'),
      () => 'it is blue, indigo, violet or something'
    )
```
and I'd like it to underline "something", so I tried 

```
match(color)
    .with(
        P.union<SomeLongAssNameType>('blue', 'indigo', 'violet', 'something'),
        () => 'it is blue, indigo, violet or something'
    )
```
but that's not gonna work because it requires 2 arguments. What makes it work is:
```
match(color).with(
      P.union<
        SomeLongAssNameType,
        [
          SomeLongAssNameType,
          SomeLongAssNameType,
          SomeLongAssNameType,
          SomeLongAssNameType
        ]
      >('blue', 'indigo', 'violet', 'something'),
      () => 'it is blue, indigo, violet or something'
    )
```
Isn't that a bit too excesive?

**Comment by gvergnaud** [comment]
Hi! 

I agree explicitly passing type parameters to `P.union` is too verbose. They are actually meant to be inferred by TypeScript and not passed manually, which is what explains their complexity. The issue is that for technical reasons, type inference only works when `P.union` is used inside a data-structure, like an object (`{  prop: P.union(...) }`), but not when passed as direct parameter to `.with()` (`.with(P.union(...), ...)`). 

In your case, you have 2 ways to work around this limitation:

`.with` supports several patterns at the top level, so instead of writing `.with(P.union(a, b, c), h)` you can write the equivalent `.with(a, b, c, h)`:

```ts
match(color).with(
  'blue',
  'indigo',
  'violet',
  'something',
  () => 'it is blue, indigo, violet or something'
)
```

The `P` module also has an undocumented `P.typed()` function that lets you specify the input type manually when typescript isn't able to infer it on its own. it looks like this `P.typed<T>().union(...)`, and with your example:

```ts
match(color).with(
  P.typed<SomeLongAssNameType>().union('blue', 'indigo', 'violet', 'something'),
  () => 'it is blue, indigo, violet or something'
)
```


The reason why `P.union` has 2 parameters is because TypeScript can sometimes instantiate the first parameter from the context in which the function is being used. The signature of `P.union` looks more or less like this:
```ts
function union<Input, Ps extends Pattern<Input>[]>(...patterns: Ps): PUnion<Input, Ps>;
```

In most contexts, `Input` can be instantiated automatically by TypeScript as the input type of the whole match expression, but for a reason I don't fully understand, it doesn't work when `P.union` is passed as a direct parameter to `.with`.

The second parameter `Ps` is the precise type of patterns you are using, which should be a subtype of `Pattern<Input>`, so we need `Input` to be properly instantiated for this type to be correct.

Hope that helps! Cheers
