### ISSUE TITLE
Exhaustiveness checking on a generic

### ISSUE THREAD

**Issue by thewilkybarkid** [gvergnaud/ts-pattern#111]
I've been trying out the latest fp-ts release candidate and found that [this change](https://github.com/gcanti/fp-ts/pull/1584) caused a failure (https://github.com/gcanti/fp-ts/pull/1584#issuecomment-1252083443).

I've narrowed the problem down to that ts-pattern's exhaustiveness checking doesn't seem to work with generics. [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzhMNgQHZwIYGc4DycAvnAGZQQhwDkZYAtDLjQFCiSyJwjYwDGACxLlK1GswZg+MAKZQMbdhjlQy2frLgAVAJ5gtCVnDhRZ2ACaYANrrjALALlqZZNOAB9aMAO4Q2xKysAPTBcADq0ADWuAA0cABGAK7w-NhJuLIWcGCUCdayIPjWwFFagjAwYLiOoQDmwDCCSQkAdPxUwXVpKsDB9Ey4wcC4uEmyQwCMAKwAHADM9lgDzHAAPABMrZPzrGRJGPxomHBW2oLAGHWTABTYznoGAJTOBK0EqOgYaxhJIAnyAB8iGMplkMCSCh4fCEdyeoJMrR8jUENyQDmcNFc7mI8RuTzgAF5gW9cFRZDdJk94SZEcimmj7E5vH4cXiCcTCK0ySAKRtqQi4K1ZAAPQTpXBoABuFPhgRCYQASrJchALEkjl9kGQ4E0tOpgNZIVpLnAKlUavUUS12p1uthev1GMxgmAktZrMEZrMACwAYhGY1kHRAvJUDEmG2mGwADAsfT7dvtDscsGcLlcNmtHrINnBRXIMBZ8DnAXcHvotF4c-zXu9Ppgfn8AVBgUYTGYIVDeAJUdgabSkSjGRiXBg3CR2USSdzyZSBbShfTUejmRJWZO4Pjp1yeXyF4PReKMtLZax5aE4ABhB1wNIZLSSaSVeRYGAQcjYQ1wZdwABWJ66oIWh1LI45QMA-CtDoFz4LgggQO62QAj+0QAPxbjQDjuD0EiJFoDq6E0lx1MgepQEBt5YuO7jQCy-hofCyaaic6YkfM2aVnmBZgcWOiVmW9z8QYtZch8qZNv8QIgh24KQlgPawv2gpDgyq6Ytim7bpypJzlSA50sO6n0WyW4cjOe43PyBlCkeEqnvi56sEAA)

The last function in the playground (`doThing3`) should work in theory shouldn't it?

**Comment by gvergnaud** [comment]
Hey!

Pattern matching on generic types is indeed not supported by ts-pattern. This is coming from a TS limitation: type-level expressions don't reduce until type parameters are instantiated, which means we can't check for exhaustiveness on a generic type in the body of a function: 

```ts
function g<T extends string>(a: T): string {
  
  // typescript doesn't know the type of `x` until T is instanciated
  // and it doesn't take type constraints into account.
  // ❌ doesn't type check
  const x: T extends number ? string : number = 'string'
  
  // ❌ doesn't type check because the type of x is 
  // `T extends number ? string : number` and not `string`
  return x
}
```

[Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwDwBVEFMAeUtgAmAzosVAE4xjIB8AFAIYBci6AlK+VTYgN4AoRIiGIA9GMRQAngAcsxCFVlREhOArAByVQGswcAO5SAFlilzzcYIgAGOW4nCwANm0QxS1co0gxG+ISiEoi+hB6q6po6Uoy65jLyiBAI3IzUUF5gUHChECnOAHTBkoAy5GoaxNqqieYQZhC6oilg5Ig4rJi4+ESkYCAAtgBGWBSIAPxklNTIiKz9w6OIALyIWtwzWqIliOVRVTG1yQ26iCMQjCDECWYWSdbtHqQ7tl14BCSICyNjkxu880GP0cYS+cFUtn+yFsogoWCgIAoSBwAgAvkA)

I would recommend using `.otherwise` in this case

**Comment by thewilkybarkid** [comment]
Thanks for confirming @gvergnaud!
