### ISSUE TITLE
Set exhaustive not working on type level?

### ISSUE THREAD

**Issue by darky** [gvergnaud/ts-pattern#189]
**Describe the bug**
Trying to exhaustive `Set`, but seems it's not working on type level

**Code Sandbox with a minimal reproduction case**
```ts
const s = new Set<'a' | 'b'>(['a']);

match(s)
  .with(P.set('a'), () => 123)
  .with(P.set('b'), () => 123)
  .exhaustive();
  
// This expression is not callable.
//  Type 'NonExhaustiveError<Set<"a" | "b">>' has no call signatures.ts(2349)
```

**Versions**
- TypeScript version: 5.2.2
- ts-pattern version: 5.0.5
- environment: node 20.4.0

**Comment by darrylnoakes** [comment]
First, `Set<'a' | 'b'>` means that _each_ of the Set's elements must satisfy `'a' | 'b'`, not that the _whole_ Set must satisfy only one of them. For example, `Set<number | string>` is a Set of numbers _and_ strings.

Second, `P.set(subpattern)` only matches if **all** the elements match the sub pattern. Because of this, you have handled the case of a Set with the value 'a' and a Set with the value 'b', not the case of a Set with _both_.

If you change the declaration of the Set to `const s: Set<'a'> | Set<'b'> = new Set(['a'])`, then it will work.
However, this seems like a very contrived example, so I'm not sure what exactly you're actually trying to achieve.
