### ISSUE TITLE
Object's unions with unions in keys require us to check for patterns that won't exist

### ISSUE THREAD

**Issue by nullndr** [gvergnaud/ts-pattern#258]
Take the following Typescript case:

```typescript
type Bar = {
  type: "bar";
  value: "a" | "b";
};

type Foo = {
  type: "foo";
  value: "x" | "z";
};

declare const foobar: Bar | Foo;

match(foobar)
  .with({ type: "bar", value: "a" }, () => {})
  .with({ type: "bar", value: "b" }, () => {})
  .with({ type: "bar", value: "x" }, () => {}) // does not make sense
  .with({ type: "bar", value: "z" }, () => {}) // does not make sense
  .with({ type: "foo", value: "a" }, () => {}) // does not make sense
  .with({ type: "foo", value: "b" }, () => {}) // does not make sense
  .with({ type: "foo", value: "x" }, () => {})
  .with({ type: "foo", value: "z" }, () => {});
```

The four patterns that do not make sense are required for `exhaustive()` to be used, otherwise a compiler error is thrown.

```typescript
match(foobar)
  .with({ type: "bar", value: "a" }, () => {})
  .with({ type: "bar", value: "b" }, () => {})
  .with({ type: "foo", value: "x" }, () => {})
  .with({ type: "foo", value: "z" }, () => {})
  .exhaustive(); // Error: type { type: "bar", value: "x" } is not handled, type ... is not handled
```

This looks like due to the fact that the type `KnownPattern` simply relies on the key's type used, creating an union, without having knowledge of the full pattern itself.

This case could be fixed with the following:

```typescript
match(foobar)
  .with({ type: "bar" }, ({ value }) =>
    match(value)
      .with("a", () => {})
      .with("b", () => {})
      .exhaustive(),
  )
  .with({ type: "foo" }, ({ value }) =>
    match(value)
      .with("x", () => {})
      .with("z", () => {})
      .exhaustive(),
  );
```

But this is way more verbose than what it could be.

As @JUSTIVE correctly commented on #228, it doesn't look right to not allow pattern that does not make sense.

> ```typescript
> import { match, P } from "ts-pattern";
>
> const x: string = "hello world";
> 
> match<string,string>(x)
>   .with(P.number,()=>"impossible")
>   .otherwise(()=> "always")
> ```
> 
> the pattern P.number doesn't make sense but it's still a valid pattern, whether it matters on runtime or not.

This is correct, it may be too restrictive to not allow patterns that does not make sense, still this will eventually raise an error with `exhaustive()` with more complex types as I said above.

So I would like to suggest a new method `strict()` or `matchStrict()` that won't allow patterns that don't make sense:

```typescript
type Bar = {
  type: "bar";
  value: "a" | "b";
};

type Foo = {
  type: "foo";
  value: "x" | "z";
};

declare const foobar: Bar | Foo;

match(foobar)
  .strict() // or matchStrict(foobar)
  .with({ type: "bar", value: "a" }, () => {})
  .with({ type: "bar", value: "b" }, () => {})
  .with({ type: "foo", value: "x" }, () => {})
  .with({ type: "foo", value: "z" }, () => {})
  .exhaustive(); // All good here, as we know
```

**Comment by gvergnaud** [comment]
I don't reproduce this issue: [Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbxAQxgYwBZwL5wGZQQhwDkMAzgLRiowCmUAdiQFAswCeYdcAQslDgBeRCzhxO3AFxwARACMBsgNxi4AN2QAbAK50Zs5LLgAfOfJUtsq9lx4AxCBGGjxk-XLxPL4zbo+yAB7GZrIAXpbWbAAmdGhaAjxoEIzk8F4QilAy-IJmjhA2KOgYABQZWQCUagB0AO7AMGUIEnYGWbIANBraegZGON2llcIAfIjY1eL1jc2t0uZK3X595sbYQyNC4wiTtQ1NpS3uBhldPf4GwYNww2MTU3Azh8dtnt7LvQERN3fbD7U6IEMMgdGlgOo6MNlEA)

Are you sure you have `"strict": true` in your tsconfig.json?

**Comment by JUSTIVE** [comment]
I can reproduce same issue what @nullndr claims. even in typescript@next
![image](https://github.com/gvergnaud/ts-pattern/assets/7118300/d101495c-075b-4c0f-8eaf-a21abc597906)

the point is, value cannot be z when type is foo. so that pattern { type:foo, value:z } never be matched, must be marked as compile error by typescript type checker.

**Comment by gvergnaud** [comment]
To clarify I don't reproduce the claim that `.exhaustive()` doesn't consider the expression exhaustive when there's an invalid pattern in the list, which I agree would be a bug.

Patterns that match invalid sets of properties are allowed in TS-Pattern. That's not ideal, but this enables better autocomplete suggestion results, better type-checking performance and makes it possible to match several branches at once when matching on data structures that have deeply nested properties in common.

TS-Pattern used to reject these cases and I intentionally change it to what it is today because it thought (and still think) that this was the best tradeoff.

**Comment by JUSTIVE** [comment]
oh yes. I missed that part. indeed that must be tsconfig issue.

**Comment by nullndr** [comment]
I see, I'm going to close this issue. Thanks to both!
