### ISSUE TITLE
Array element matching bug on empty arrays

### ISSUE THREAD

**Issue by oguimbal** [gvergnaud/ts-pattern#46]
Hi !

**Describe the bug**
```typescript
import { match, __, not } from 'ts-pattern';

console.log(match([]) // Logs 👉 first
  .with([__], () => 'first')
  .otherwise(() => 'default'));

console.log(match([]) // Logs 👉 first
  .with([not(__.nullish)], () => 'first')
  .otherwise(() => 'default'));
```

Even if the first is a bit ambiguous, I would at least expect the second one NOT to print "first"... 

**Code Sandbox with a minimal reproduction case**

https://codesandbox.io/s/icy-glade-3ty9l?file=/src/index.ts

**Versions**
- TypeScript version: 4.3.4
- ts-pattern version: 3.2.5
- environment: any

**Comment by gvergnaud** [comment]
I agree this behavior is confusing, but it's expected. `[subpattern]` patterns are **list** patterns, matching any list in which all elements match the subpattern, including empty lists. If you want to match empty lists separately a workaround is to add a `.with([], handler)` clause before your `[__]` pattern.

In retrospect, I don't think this was a great API choice because it can be confused with an unary tuple pattern (a pattern matching a list with a single element). I've been thinking about introducing a separate `list(subpattern)` helper that would look like this:

```ts
import { match, list, __ } from 'ts-pattern';

match(someList)
   .with([], () => 'empty list')
   .with([__], () => 'list with a single element')
   .with(list(not(null)), () => 'list with n elements')
   .exhaustive();
```

But this would be a breaking change, which makes it a bit tricky to release.

**Comment by oguimbal** [comment]
It would be tricky indeed 🤔

That said, it would be more intuitive, IMO.  
And it would match Haskells behaviour.

Maybe for ts-pattern v4 🥳 ?

**Comment by gvergnaud** [comment]
Closing since TS-Pattern v4 has been released and fixes this problem. [Release note](https://github.com/gvergnaud/ts-pattern/releases/tag/v4.0.1)
