### ISSUE TITLE
Chaining patterns with logical operators

### ISSUE THREAD

**Issue by joshuabowers** [gvergnaud/ts-pattern#61]
**Is your feature request related to a problem? Please describe.**
consider the following class hierarchy:
```ts
abstract class N {
  a: N
  b: N
}

class A extends N {
}

class B extends N {
}
```

Using the `instanceOf` pattern, it's possible to match an exact instance of either `A` or `B` directly, or as a child at some point in the tree:

```ts
const a = new A()

const found = match<N, N>(a)
  .with(instanceOf(A), (v) => {console.log('got an A'); return v})
  .run()

const deepFind = match<N, N>(a)
  .with({a: instanceOf(A), b: instanceOf(B)}, (v) => {console.log('v is either A or B, a is an A, b is a B'); return v})
  .run()
```

However, there does not seem to be a way to do both of these together to narrow the types (at least, to such an extent that an IDE might be able to correctly narrow for tooltips). 

**Describe the solution you'd like**
Some sort of `and` / `intersect` pattern, similar in concept to what `not` is doing: it would take multiple patterns as arguments, and each of them must pass to correctly narrow the type. This suggests a further possibility: `or` / `union` for broadening types. This is, of course, assuming that such functionality would correctly trigger the type inference functionality of TypeScript.

So, `deepFind` might look like:
```ts
const deepFind = match<N, N>(a)
  .with(and(instanceOf(A), {a: instanceOf(B), b: instanceOf(B)}), (v) => {console.log('got an A with {a, b} both B'); return v})
```

**Describe alternatives you've considered**
`deepFind`, above, could be done with a slight alteration to the class hierarchy:
```ts
abstract class N {
  type: string
  a: N
  b: N
}

class A extends N {
  type = 'A'
}

class B extends N {
  type = 'B'
}
```

Then, when doing a structural search, one could pattern match on `tyoe` and  assert the instance types of the other properties:

```ts
const deepFind = match<N, N>(a)
  .with({type: 'A', a: instanceOf(B), b: instnaceOf(B)}, (v) => {console.log('an A instance with {a, b} both B'; return v})
  .run()
```

This works currently, but requires extra data be stored in each class instance, while also requiring more set up on each class. For this case the extra effort is trivial; for more expansive class hierarchies or larger datasets, it would be more cumbersome.

I'm aware that `with` can take a guard predicate as an optional second parameter, but, to my knowledge, that does not affect type narrowing. Further, I don't believe narrowing would necessarily be done on use of a `when` predicate, should something like the following be done:

```ts
const deepFind = match<N, N>(a)
  .when((v) => v instanceOf(A) && v.a instanceOf(A), (v) => {console.log('is either v or v.a narrowed? Is this safe? what happens if v.a undefined?'); return v})
  .run()
```

**Additional context**
My apologies if some of this seems discombobulated: most of this is written in the context of IntelliSense feedback from VS Code; some of the above might work correctly even if the editor is unable to provide proper feedback about it.

**Comment by gvergnaud** [comment]
Hey, nice suggestion!

I've been meaning to add the `and` and `or` functions you described in your issue to the lib for a little while. I would very much like to find a good way to do this, but currently I'm struggling with finding a good implementation that has all the properties I want to preserve:

- the pattern shape should be inferred from the input type, so that typescript can help you constructing your pattern by providing helpful suggestions and so that you can't write an invalid pattern that will never match anything.
- The pattern should should precisely describe the type of values it handles, meaning it shouldn't be possible to write a pattern that matches more (or less) values than what the type is telling you.

Ideally I'd like to also add a `optional` and a `list` function following the same principles, and reserve `[subpattern]` for unary tuples.


> I'm aware that with can take a guard predicate as an optional second parameter, but, to my knowledge, that does not affect type narrowing.

FYI It does, but the predicate needs to be a type guard function (a function with a return type like `arg is SomeType`).

**Comment by gvergnaud** [comment]
Closing since TS-Pattern v4 has been released and adds `P.union` and `P.intersection` for boolean logic on patterns. [Release note](https://github.com/gvergnaud/ts-pattern/releases/tag/v4.0.1)
