### ISSUE TITLE
Exhaustive check fails with tuple of tuples

### ISSUE THREAD

**Issue by finalclass** [gvergnaud/ts-pattern#69]
**Describe the bug**
While matching against a tuple that has a tuple and the inner tuple has variable number of elements, the exhaustive check fails.

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/romantic-architecture-39wbm

However this works fine:
https://codesandbox.io/s/aged-field-vrldb

So it can be seen that if in a tuple we have a tuple which size varies then it fails the exhaustive check.

**Versions**
- TypeScript version: 4.5.4
- ts-pattern version: 3.3.4
- environment: not related, it fails compilation

**Comment by gvergnaud** [comment]
👋 Thanks for the report.

That's actually because ts-pattern v3 doesn't support unary tuples (tuples containing a single element, like your `[type: "Login"]` type). those patterns are currently considered ["list" patterns](https://github.com/gvergnaud/ts-pattern#lists-arrays), which means they will match lists of variable length, as long as all elements in the array match the sub-pattern (`"Login"` in your case). 

This is a pretty confusing behavior and this will change in v4. see this related comment https://github.com/gvergnaud/ts-pattern/issues/46#issuecomment-917597868

**Comment by finalclass** [comment]
Thanks for your answer and a for this wonderful library:)
Do you have any roadmap/release date for v4?

**Comment by gvergnaud** [comment]
Nope, I only started working on it during this Christmas holidays. 

I'm still experimenting with ideas at this point and I don't want to broadly communicate about it or commit to a release date until I'm sure what I want to do is technically feasible :) But I'm pretty confident it will be released in 2022
