### ISSUE TITLE
Would it be possible to get rid of run?

### ISSUE THREAD

**Issue by jkavalec** [gvergnaud/ts-pattern#8]
Hi, I am really impressed with this library, great job!

I have just tiny cosmetic issue, that is not preventing me from using library at all but...

Would it be possible to make  run() on patterns without otherwise() hidden so it doesn't hang in there like some ugly tail?

**Comment by gvergnaud** [comment]
Hey! 

Unfortunately the library needs a way to know if you want to get back the value or if you want to keep chaining matching cases, and `run` is there to extract the value. There is no way to automagically infer what we should return that I know of, but if you come back with a suggestion I'd be glad to hear about it 🙂

**Comment by jkavalec** [comment]
Hi,

I'll be looking into sources, and if I have an idea how to do it, I'll let you know. This is the best small library since immerjs for sure for me 🥇

**Comment by MikelArnaiz** [comment]
Hi I'd like to introduce `ts-pattern` to my project but I'm worried about potential bugs.
In React, if I forget adding `.run`, `.otherwise` or `.exhaustive` I don't get any type error.

![Screenshot 2021-11-15 at 12 28 22](https://user-images.githubusercontent.com/2076221/141774493-769fee28-7a7d-43d3-b255-8a74be07addc.png)

Is there a way to prevent this?

So far I can only think of creating a wrapper function.

![Screenshot 2021-11-15 at 12 52 32](https://user-images.githubusercontent.com/2076221/141777574-84b5ac57-3f29-4a69-b064-091a61841d55.png)

It's less than optimal, but at least I get an error:

```
Argument of type 'Match<number, "@ts-pattern/unset", [123, any], Element>' is not assignable to parameter of type 'Element'.
  Type 'Match<number, "@ts-pattern/unset", [123, any], Element>' is missing the following properties from type 'Element': type, props, keyts(2345)
```

**Comment by gvergnaud** [comment]
TS-Pattern isn't meant to only be used in the context of react, so it can return anything. Looks likes React types accept any object as valid JSX elements and this isn't something the library can influence. Your solution looks good to me, and unfortunately I don't see any ways to solve that by updating the library code

**Comment by MikelArnaiz** [comment]
Indeed the problem is that `ReactNode` includes `ReactFragment` which is `{} | ReactNodeArray`.
I did try passing `JSX.Element` to the second generic of `match` but that doesn't solve anything as I still get a `Match`.

I wonder if some changes in typing might make something like what `renderMatch` does accomplishable.
